language: ruby
rvm:
- 2.3.3

script: bundle exec jekyll build

deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: gjhr.me
  skip_cleanup: true
  local_dir: _site