baseURL = 'https://gjhr.me/'
languageCode = 'en-gb'
title = "George Richardson's Blog"
description = 'Hopefully an interesting blog...'
uglyurls = true
rssLimit = 5
[Author]
  name = 'George Richardson'

markup.goldmark.renderer.unsafe = true

[permalinks]
  posts = '/:year/:month/:day/:title'

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
[outputFormats.newsletter]
name = "newsletter"
mediatype = "application/xml"
path = "newsletter"
baseName = "newsletter"
isPlainText = true
rel = "alternate"
isHTML = false
noUgly = true
permalinkable = false

[outputs]
  home = ['HTML', 'RSS', 'newsletter']

[deployment]
[[deployment.targets]]
name = "s3"
URL = "s3://gjhr.me-origin?region=eu-west-1"
cloudFrontDistributionID = "E11P1M7WP9K2ED"
