baseURL = 'https://gjhr.me/'
languageCode = 'en-gb'
title = "George Richardson's Blog"
description = 'Hopefully an interesting blog...'
uglyurls = true

markup.goldmark.renderer.unsafe = true

[permalinks]
  posts = '/:year/:month/:day/:title'

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[deployment]
[[deployment.targets]]
name = "s3"
URL = "s3://gjhr.me-origin?region=eu-west-1"
cloudFrontDistributionID = "E11P1M7WP9K2ED"
