name: BuildAndDeploy

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Terraform
        run: ./.github/scripts/deploytf.sh
        shell: bash
      - name: Deploy Website
        run: ./.github/scripts/deployhugo.sh
        shell: bash
