name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - infra
  schedule: 
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::000106928613:role/GitHub
          role-session-name: gjhr-publish
          aws-region: eu-west-1
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Publish
        run: hugo deploy
